app/urls.py
from django.conf.urls import url
from app import views
#from rest_framework.routers import SimpleRouter

# router = SimpleRouter()
# router.register(r'^cart', views.CartEdit)
app_name='[axf]'
urlpatterns = [
    url(r'home/',views.Home,name='home'),
    url(r'market/',views.Market,name='market'),
    # 闪购分类
    url(r'markettype/',views.MarketType,name='markettype'),
    url(r'market_childtype_order/',views.Market_ChildType_Order,name='market_childtype_order'),
    # 购物车
    url(r'cart/',views.Cart,name='cart'),
    # 个人中心
    url(r'mine/',views.Mine,name='mine'),
    # 登录
    url(r'login/',views.Login,name='login'),
    # 退出
    url(r'logout/',views.Logout,name='logout'),
    # 注册
    url(r'register/',views.Register,name='register'),
    # 添加商品到购物车
    url(r'addgoods/',views.add_goods,name='addgoods'),
    url(r'subgoods/',views.sub_goods,name='subgoods'),
    # 修改购物车商品的选择
    url(r'changecartselect/',views.user_chang_select,name='change_select'),
    url(r'changecartselectall/',views.user_chang_selectAll,name='change_selectall'),
    # 下单
    url(r'generateorder/',views.user_generate_order,name='user_generate_order'),
    # 付款
    url(r'payorder/(\d+)/',views.user_pay_order,name='user_pay_order'),
    url(r'orderpayed/(\d+)/',views.order_pay,name='order_pay'),
    url(r'orderWaitPay/',views.order_wait_pay,name='order_wait_pay'),
    url(r'orderlistpayed/',views.order_wait_shouhuo,name='order_wait_shouhuo'),
]
# urlpatterns += router.urls

pankx_axf/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import static
from django.views.static import serve
from pankx_axf import settings
from app import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'axf/',include('app.urls',namespace='axf')),
    url(r'static/(?P<path>.*)$',serve,{"document_root":settings.STATIC_ROOT},),
    url(r'media/(?P<path>.*)$',serve,{"document_root":settings.MEDIA_ROOT},),
    url(r'^$',views.Home)
]

app/models.py
from django.db import models
from django.db import models

# Create your models here.

class Main(models.Model):
    img = models.CharField(max_length=200)  # 图片
    name = models.CharField(max_length=100)  # 名称
    trackid = models.CharField(max_length=16)  # id

    class Meta:
        abstract = True

class MainWheel(Main):
    class Meta:
        db_table = 'axf_wheel'

class MainNav(Main):
    class Meta:
        db_table = 'axf_nav'

class MainHotGoods(Main):
    class Meta:
        db_table = 'axf_hotgoods'

class MainShop(Main):
    class Meta:
        db_table = 'axf_shop'

class MainMustBuy(Main):
    class Meta:
        db_table = 'axf_mustbuy'

class MainShow(Main):
    categoryid = models.CharField(max_length=16,null=True)
    brandname = models.CharField(max_length=100,null=True)
    img1 = models.CharField(max_length=200)
    childcid1 = models.CharField(max_length=16,null=True)
    productid1 = models.CharField(max_length=16,null=True)
    longname1 = models.CharField(max_length=100)
    price1 = models.FloatField(default=0)
    marketprice1 = models.FloatField(default=1)
    img2 = models.CharField(max_length=200)
    childcid2 = models.CharField(max_length=16,null=True)
    productid2 = models.CharField(max_length=16,null=True)
    longname2 = models.CharField(max_length=100)
    price2 = models.FloatField(default=0)
    marketprice2 = models.FloatField(default=1)
    img3 = models.CharField(max_length=200)
    childcid3 = models.CharField(max_length=16,null=True)
    productid3 = models.CharField(max_length=16,null=True)
    longname3 = models.CharField(max_length=100)
    price3 = models.FloatField(default=0)
    marketprice3 = models.FloatField(default=1)

    class Meta:
        db_table = 'axf_mainshow'

# 闪购左侧模型
class FoodType(models.Model):
    typeid = models.CharField(max_length=60)
    typename = models.CharField(max_length=100)
    childtypenames = models.CharField(max_length=200)
    typesort = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_foodtypes'


class Goods(models.Model):
    productid = models.CharField(max_length=16)  # 商品的id
    productimg = models.CharField(max_length=200)  # 商品的图片
    productname = models.CharField(max_length=100)  # 商品的名称
    productlongname = models.CharField(max_length=200)  # 商品的规格
    isxf = models.IntegerField(default=1)
    pmdesc = models.CharField(max_length=100)
    specifics = models.CharField(max_length=100)  # 规格
    price = models.FloatField(default=0)  # 商品的折后价格
    marketprice = models.FloatField(default=1)  # 商品的原价
    categoryid = models.CharField(max_length=16)  # 分类的id
    childcid = models.CharField(max_length=16)  # 子分类的id
    childcidname = models.CharField(max_length=100)  # 子分类的名称
    dealerid = models.CharField(max_length=16)
    storenums = models.IntegerField(default=1)  # 排序
    productnum = models.IntegerField(default=1)  # 销量排序

    class Meta:
        db_table = 'axf_goods'

class UserModel(models.Model):
    username = models.CharField(max_length=32,unique=True)
    password = models.CharField(max_length=256)
    email = models.CharField(max_length=64, unique=True)
    # Falsh代表女
    sex = models.BooleanField(default=False)
    icon = models.ImageField(upload_to='icon')
    is_delete = models.BooleanField(default=False)
    ticket = models.CharField(max_length=30,null=True)

    class Meta:
        db_table = 'axf_user'

# 购物车
class CarModel(models.Model):
    user = models.ForeignKey(UserModel,on_delete=models.CASCADE)  # 关联用户
    goods = models.ForeignKey(Goods,on_delete=models.CASCADE)  # 关联商品
    c_num = models.IntegerField(default=1)  # 商品的个数
    is_select = models.BooleanField(default=True)  # 是否选择商品

    class Meta:
        db_table = 'axf_cart'

class OrderModel(models.Model):
    user = models.ForeignKey(UserModel,on_delete=models.CASCADE)  # 关联用户
    o_num = models.CharField(max_length=64)  # 数量
    # 0 代表下单，但是未付款 1 代表已付款未发货 2 已付款。已发货
    o_status = models.IntegerField(default=0)  # 状态
    o_create = models.DateTimeField(auto_now_add=True)  # 创建时间

    class Meta:
        db_table = 'axf_order'


class OrderGoodsModel(models.Model):
    goods = models.ForeignKey(Goods,on_delete=models.CASCADE)  # 关联的商品
    order = models.ForeignKey(OrderModel,on_delete=models.CASCADE)  # 关联的订单
    good_num = models.IntegerField(default=1)  # 商品的个数

    class Meta:
        db_table = 'axf_order_goods'

class UserTicketModel(models.Model):
    user = models.ForeignKey(UserModel,on_delete=models.CASCADE)
    ticket = models.CharField(max_length=30,null=True)
    out_time = models.DateTimeField()

    class Meta:
        db_table = 'axf_user_ticket'

templates/order/order_info.html
{% extends 'base.html' %}
{% load static %}

{% block EXTJS %}
{#    <script type="text/javascript" src="{% static 'app/order/js/order.js' %}"></script>#}
{% endblock %}

{% block content %}

    <div id="order_info" class="container">

    <!--订单编号-->
    <h3>订单编号:{{ order_id }}</h3>
    <!--处理结束-->
    <ul>

        <!--所有订单信息展示-->
        {% for ordergood in orders.ordergoodsmodel_set.all %}
            <li>
                <!--商品名称展示-->
                <img src="{{ ordergood.goods.productimg }}">

                <span style="font-size: 22px;display: inline-block;width: 400px"> <!-- 数量展示 -->商品数量: {{ ordergood.good_num }}商品名称: {{ ordergood.goods.productlongname }}</span>
            </li>
        {% endfor %}
        <!--订单处理结束-->

    </ul>
        <!--订单id展示-->
    <a href="/axf/orderpayed/{{ order_id }}">
        <button id="alipay" class="btn btn-success btn-block">Alipay</button>
</a>
    </div>


{% endblock %}

templates/order/order_list_payed.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待收货订单列表</h3>

    <ul>
        <!--订单展示-->
        {% for order in orders %}
            <li style="margin-bottom: 20px">
                <div style="height: 2px; width: 100%; border: 1px solid blue;clear: both;"></div>
                    <p style="font-size: 32px; text-align: center;color: orangered">订单id: {{ order.id }}</p>
                <div style="height: 2px; width: 100%; border: 1px solid blue;"></div>
                    {% for ordergoods in order.ordergoodsmodel_set.all %}
                        <div style="margin-top: 20px">
                            <p style="font-size: 24px;float: left;width: 500px;height: 200px;margin: 0">商品数量: {{ ordergoods.good_num }}<br/><br/>商品名称: {{ ordergoods.goods.productlongname }}</p>
                        <!--展示商品的名称-->
                            <img src="{{ ordergoods.goods.productimg }}" alt="">
                        </div>
                        <!--处理结束-->
                    {% endfor %}
            <span style="clear: both"><a href="#" style="font-size: 28px;">确认收货</a></span>
            </li>
        {% endfor %}
        <!--订单处理结束-->

    </ul>


{% endblock %}

templates/order/order_list_wait_pay.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待付款订单列表</h3>

    <ul>
        <!--订单信息展示-->
        {% for order in orders %}
            <div style="height: 2px; width: 100%; border: 1px solid blue;clear: both;"></div>
            <p style="font-size: 32px; text-align: center;color: orangered">订单id:{{ order.id }}</p>
            <div style="height: 2px; width: 100%; border: 1px solid blue;"></div>
            <li style="margin-bottom: 60px;">
                {% for ordergoods in order.ordergoodsmodel_set.all %}
                <div style="margin-top: 10px">
                    <p style="font-size: 24px;float: left;width: 400px;height: 200px">商品数量:{{ ordergoods.good_num }}<br/><br/>商品名称:{{ ordergoods.goods.productlongname }}</p>
                    <!--展示商品的名称-->
                    <img src="{{ ordergoods.goods.productimg }}" alt="">
                </div>
                <div style="height: 4px; width: 100%; border: 1px solid black;clear: both"></div>
                <!--处理结束-->
                {% endfor %}
                <a href="{% url 'axf:user_pay_order' order.id %}" style="height: 40px;width: 110px;background: red;color: white;float: right;font-size: 24px;text-align: center;">立即付款</a>
            </li>
        {% endfor %}
        <!--订单处理结束-->


    </ul>


{% endblock %}