app/urls.py
from django.conf.urls import url
from app import views
#from rest_framework.routers import SimpleRouter

# router = SimpleRouter()
# router.register(r'^cart', views.CartEdit)
app_name='[axf]'
urlpatterns = [
    url(r'home/',views.Home,name='home'),
    url(r'market/',views.Market,name='market'),
    # 闪购分类
    url(r'markettype/',views.MarketType,name='markettype'),
    url(r'market_childtype_order/',views.Market_ChildType_Order,name='market_childtype_order'),
    # 购物车
    url(r'cart/',views.Cart,name='cart'),
    # 个人中心
    url(r'mine/',views.Mine,name='mine'),
    # 登录
    url(r'login/',views.Login,name='login'),
    # 退出
    url(r'logout/',views.Logout,name='logout'),
    # 注册
    url(r'register/',views.Register,name='register'),
    # 添加商品到购物车
    url(r'addgoods/',views.add_goods,name='addgoods'),
    url(r'subgoods/',views.sub_goods,name='subgoods'),
    # 修改购物车商品的选择
    url(r'changecartselect/',views.user_chang_select,name='change_select'),
    url(r'changecartselectall/',views.user_chang_selectAll,name='change_selectall'),
    # 下单
    url(r'generateorder/',views.user_generate_order,name='user_generate_order'),
    # 付款
    url(r'payorder/(\d+)/',views.user_pay_order,name='user_pay_order'),
    url(r'orderpayed/(\d+)/',views.order_pay,name='order_pay'),
    url(r'orderWaitPay/',views.order_wait_pay,name='order_wait_pay'),
    url(r'orderlistpayed/',views.order_wait_shouhuo,name='order_wait_shouhuo'),
]
# urlpatterns += router.urls

pankx_axf/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import static
from django.views.static import serve
from pankx_axf import settings
from app import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'axf/',include('app.urls',namespace='axf')),
    url(r'static/(?P<path>.*)$',serve,{"document_root":settings.STATIC_ROOT},),
    url(r'media/(?P<path>.*)$',serve,{"document_root":settings.MEDIA_ROOT},),
    url(r'^$',views.Home)
]

templates/mine/mine.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/mine/mine.css' %}">
{% endblock %}

{% block EXTJS %}
{{ block.super }}
    <script type="text/javascript" src="{% static 'app/mine/js/mine.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="mine">

        <div class="fixed">
            {% if request.session.user.pk %}
            <!--如果登录，展示头像-->
                <img src="/media/{{ request.session.user.icon }}/" alt="icon">
            {% else %}
            <!--或者-->
                <span class="glyphicon glyphicon-user"></span>
            <!--判断结束-->
            {% endif %}
            {% if request.session.user.pk %}
            <!--如果登录，展示姓名-->
                <p>{{ request.session.user.username }}</p>
            {% else %}
            <!--或者展示登录的链接-->
                <a href="{% url 'axf:login' %}">登录</a>
            <!--判断结束-->
            {% endif %}

            {% if request.session.user.pk %}
            <p><span class="glyphicon glyphicon-fire"></span><span>等级</span></p>
            <!--如果没有登录,展示注册信息-->
            {% else %}
                <div id="regis">
                    <a href="{% url 'axf:register' %}">注册</a>
                </div>
            <!--判断结束-->
            {% endif %}

            <p><span class="glyphicon glyphicon-heart"></span><span>收藏</span></p>

        </div>

        <div class="mine">

            <p>我的订单<a href="#">更多&gt;</a></p>

            <div id="nav">
                <ul>
                    <a href="/axf/orderWaitPay/">
                    <li>
                        <dl>
                            <dt><span id="wait_pay_list" class="glyphicon glyphicon-usd"></span>
                                <span class="badge">
                                    <!--代付款的数量-->
                                    {{ wait_pay }}
                                </span></dt>
                            <dd>待付款</dd>
                        </dl>

                    </li>
                    </a>
                    <a href="/axf/orderlistpayed/">
                    <li>
                        <dl>
                            <dt><span id="order_payed_list" class="glyphicon glyphicon-envelope"></span>
                                <span class="badge">
                                    <!--待收货的数量-->
                                    {{ payed }}
                                </span></dt>
                            <dd>待收货</dd>
                        </dl>

                    </li>
                    </a>
                    <a>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-pencil"></span></dt>
                            <dd>待评价</dd>
                        </dl>

                    </li>
                    </a>
                    <a>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-retweet"></span></dt>
                            <dd>退款/售后</dd>
                        </dl>

                    </li>
                    </a>

                </ul>

            </div>

            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
                            <span>积分商城</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-credit-card"></span></dt>
                            <span>优惠券</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-import"></span></dt>
                            <span>收货地址</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
                            <span>客户反馈</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-certificate"></span></dt>
                            <span>关于我们</span>
                        </dl>
                    </li>
                </ul>
            </menu>

            <!--如果登录了,则退出展示-->
            {% if user.pk %}
                <p class="logout">
                    <a href="{% url 'axf:logout' %}">退出</a>
                </p>
            <!--判断结束-->
            {% endif %}
        </div>
    </div>


{% endblock %}